branch:HPCC-27615-easy-deploy-bryan4-placing-auto.tfvars-files-aks-storage

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -6,6 +6,15 @@ if [ "$1" != "" ] && [[ $1 =~ hpcc|aks|vnet|storage ]];then
 else
   echo "$0 has no arguments. It must of 1 argument that is 'vnet' or 'storage' or 'aks' or 'hpcc'. EXITING.";exit 1;
 fi
+if [ "$1" == "aks" ];then
+  if [ "$2" != "" ];then
+    my_azure_id=$2
+    cp -v $thisdir/needed-auto.tfvars-files/aks/*.auto.tfvars $repodir/aks
+    sed -i "s/<my_azure_id>/$my_azure_id/" $repodir/aks/aks.auto.tfvars
+  else
+    echo "In $0. First argument was \"$name\". There should be a 2nd argument (my_azure_id). But it was missing. EXITING.";exit 1;
+  fi
+fi
 #========================================================================
 function assert_fail () {
     echo ">>>>>>>>>>>>>>> EXECUTING: $*"
@@ -59,7 +68,7 @@ done
 
 cd $name; # cd into vnet or storage or aks or hpcc
 
-# put the root directory's lite.auto.tfvars (either all of part) in either aks or hpcc
+# put the root directory's lite.auto.tfvars (either all or part) in either aks or hpcc
 # directory.
 if [ -e "../lite.auto.tfvars" ];then 
   # Check if there has been a change since last apply.
@@ -80,6 +89,9 @@ elif [ "$name" == "aks" ] || [ "$name" == "vnet" ] || [ "$name" == "storage" ];t
     egrep "^aks_" ../lite.auto.tfvars > /tmp/${name}.lite.auto.tfvars
     egrep "^aks_" ../lite.auto.tfvars > lite.auto.tfvars
     ../scripts/extract-aks-variables ../lite-variables.tf > lite-variables.tf
+    if [ "$name" == "storage" ];then
+       cp -v $thisdir/needed-auto.tfvars-files/storage/*.auto.tfvars .
+    fi
 fi
 #------------------------------------------------------------------------
 if [ ! -d "$HOME/tflogs" ];then
